servers:
  - name: webserver
    security_groups: "couchdb,ssh,django-dev"
    groups: dbservers,harvestservers,webservers

  - name: harvester
    security_groups: "couchdb,ssh"
    groups: dbservers,harvestservers

security_groups:
  - name: ssh
  - name: couchdb
  - name: django-dev

security_group_rules:
  - security_group: ssh
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

  - security_group: couchdb
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

  - security_group: couchdb
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_group: couchdb

  - security_group: couchdb
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_group: couchdb

  - security_group: django-dev
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0